#!/usr/bin/env sh

if [ ! -d ~/.emacs.d ]; then
git clone --depth 10 --branch develop --single-branch https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

for dir in */
do
	stow --verbose --target ~/ -S $dir
done
